"""Recommendation entity — the user-facing output of the scoring pipeline."""

from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict, Field

from src.contracts.entities.score import CompositeScore
from src.contracts.entities.signal import Signal

ActionLabel = Literal["STRONG BUY", "BUY", "HOLD", "SELL", "STRONG SELL"]
"""From src/scoring/recommender.py:_determine_action."""

ConfidenceLabel = Literal["High", "Medium-High", "Medium", "Low"]
"""From src/scoring/recommender.py:_determine_action."""

OrderType = Literal["Limit", "Stop", "Market"]


class RiskManagement(BaseModel):
    """Stop loss + take profit + position sizing + R/R for a single
    recommendation. Mirrors the dict shape from
    src/scoring/recommender.py:_calculate_risk_management."""

    model_config = ConfigDict(frozen=True)

    current_price: float
    stop_loss: dict = Field(default_factory=dict)
    """Sub-dict: {price, method, pct_from_current, ...}. Stays as dict
    until Phase 0 parity is locked; narrows in a follow-up."""
    take_profit: dict = Field(default_factory=dict)
    position_size: dict = Field(default_factory=dict)
    risk_reward: dict = Field(default_factory=dict)


class OrderInstruction(BaseModel):
    """Step-by-step broker instructions for a single recommendation.

    Generated by the recommender for BUY/STRONG BUY actions. Web layer
    will render these as cards; CLI uses src/presentation/cli/panels.
    """

    model_config = ConfigDict(frozen=True)

    order_type: OrderType
    entry_price: float
    stop_loss_price: float
    take_profit_price: float
    qty: int = Field(ge=0)
    steps: tuple[str, ...] = ()
    rationale: str = ""


class Recommendation(BaseModel):
    """Full investment recommendation for a single ticker.

    Field-for-field replacement of the dict returned by
    src/scoring/recommender.py:generate_recommendation.
    """

    model_config = ConfigDict(frozen=True)

    ticker: str
    action: ActionLabel
    composite_score: float = Field(ge=0, le=100)
    confidence: ConfidenceLabel
    sub_scores: dict[str, float] = Field(default_factory=dict)
    breakdown: list[dict] = Field(default_factory=list)
    """ScoreBreakdownRow.model_dump() entries. Kept as list[dict] for
    backwards-compat with current display code that iterates the dicts."""

    reasoning: tuple[str, ...] = ()
    bullish_signals: int = 0
    bearish_signals: int = 0
    all_signals: tuple[Signal, ...] = ()
    risk_management: RiskManagement | None = None
    order_instruction: OrderInstruction | None = None
    """Only set for BUY / STRONG BUY actions."""

    # --- denormalized fundamentals fields for display ---
    name: str = ""
    sector: str = "Unknown"
    industry: str = "Unknown"
    market_cap: Optional[float] = None

    def legacy_dict(self) -> dict:
        """Return the legacy untyped-dict shape current call sites expect.
        Shim. Remove in Phase 1."""
        return {
            "ticker": self.ticker,
            "action": self.action,
            "composite_score": self.composite_score,
            "confidence": self.confidence,
            "sub_scores": dict(self.sub_scores),
            "breakdown": list(self.breakdown),
            "reasoning": list(self.reasoning),
            "bullish_signals": self.bullish_signals,
            "bearish_signals": self.bearish_signals,
            "all_signals": [s.model_dump() for s in self.all_signals],
            "risk_management": (
                self.risk_management.model_dump() if self.risk_management else {}
            ),
            "name": self.name,
            "sector": self.sector,
            "industry": self.industry,
            "market_cap": self.market_cap,
        }

    @classmethod
    def from_score(
        cls,
        ticker: str,
        score: CompositeScore,
        action: ActionLabel,
        confidence: ConfidenceLabel,
        reasoning: tuple[str, ...] = (),
        risk_management: RiskManagement | None = None,
        order_instruction: OrderInstruction | None = None,
        name: str = "",
        sector: str = "Unknown",
        industry: str = "Unknown",
        market_cap: Optional[float] = None,
    ) -> "Recommendation":
        """Lift a CompositeScore + recommendation-layer outputs into a typed
        Recommendation. Used by ScoringService and Stream B carve."""
        return cls(
            ticker=ticker,
            action=action,
            composite_score=score.composite_score,
            confidence=confidence,
            sub_scores=dict(score.sub_scores),
            breakdown=[b.model_dump() for b in score.breakdown],
            reasoning=reasoning,
            bullish_signals=score.bullish_signals,
            bearish_signals=score.bearish_signals,
            all_signals=score.all_signals,
            risk_management=risk_management,
            order_instruction=order_instruction,
            name=name,
            sector=sector,
            industry=industry,
            market_cap=market_cap,
        )
