/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Cheap liveness check — process is up and serving.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness check — verifies Postgres + Redis are reachable.
         *
         *     Returns 200 only when both adapters round-trip. Use this from a deploy
         *     health probe; use /health for fast process-alive checks.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description Live snapshot: account fields + current positions.
         */
        get: operations["get_portfolio_api_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Positions */
        get: operations["get_positions_api_portfolio_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account */
        get: operations["get_account_api_portfolio_account_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description Equity curve from Alpaca's portfolio history.
         *
         *     ``period`` is Alpaca's window shorthand (1D / 1W / 1M / 3M / 6M / 1A).
         *     ``timeframe`` is the bar size; intraday timeframes are silently
         *     downgraded to 1D for windows > 1W (Alpaca rejects them otherwise).
         */
        get: operations["get_history_api_portfolio_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scans
         * @description Most recent scan runs, newest first.
         */
        get: operations["list_scans_api_scans_get"];
        put?: never;
        /**
         * Trigger Scan
         * @description Run a synchronous scan and persist the result.
         *
         *     Synchronous from the caller's perspective — blocks until the scan
         *     completes. Heavy compute runs in a worker thread so the event loop stays
         *     responsive. Phase 1.7 adds /api/stream/scan-progress for live updates.
         */
        post: operations["trigger_scan_api_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/latest-buys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest Buys
         * @description Union of BUY+ rows from the latest scan per strategy.
         *
         *     Pulls the most-recent scan_run per strategy, filters each to BUY+ rows,
         *     and deduplicates by ticker — attributing each ticker to the strategy
         *     that produced its highest composite_score. ``consensus_count`` reports
         *     how many strategies' latest runs agreed on the BUY+ rating for that
         *     ticker, so the FE can highlight cross-strategy conviction.
         *
         *     Returns rows sorted by composite_score desc, consensus_count desc as
         *     tiebreak. Empty list when no recent scan has any BUY+ rows (not an
         *     error — the system simply isn't ringing the bell right now).
         */
        get: operations["latest_buys_api_scans_latest_buys_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/factor-picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Factor Picks
         * @description Today's composite-factor picks (PIT S&P 500, m+q+v rank-blend).
         *
         *     Reads from ``data/daily_picks/YYYY-MM-DD.json`` — the source the
         *     paper trader uses to place real (paper) orders. This is the
         *     canonical "what does the system want to BUY?" surface for the
         *     factor strategy. Sanity-check verdicts (cached against the
         *     synthetic ``factor:<strategy>:<as_of>`` run_id) are attached when
         *     present so the web UI can render the same brake-light pattern as
         *     the composite-path /latest-buys endpoint.
         *
         *     Returns an empty list when no picks file exists (system not yet
         *     bootstrapped) or when the file is malformed — by design, since
         *     the scoring-path /latest-buys endpoint is a viable fallback for
         *     the FE.
         */
        get: operations["factor_picks_api_scans_factor_picks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/sanity-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Sanity Check
         * @description Run the pre-trade AI sanity check over the current BuySignal set.
         *
         *     Reuses ``latest_buys`` to assemble the candidate set (same DISTINCT
         *     ON / integrity-gate filtering), then runs the check on each row in
         *     parallel, upserts results into the ``sanity_checks`` table, and
         *     returns the refreshed BuySignal list with ``sanity_check``
         *     populated.
         *
         *     Cost: ~$0.005/ticker on the live path (claude-sonnet-4-6); mock
         *     path is free. The check is asymmetric — it can downgrade BUYs to
         *     CAUTION or REJECT but never upgrade them.
         *
         *     Idempotency: ``force_refresh=false`` skips tickers that already
         *     have a cached check for their run_id. Set ``force_refresh=true``
         *     to overwrite (e.g. after re-running with the live model).
         */
        post: operations["trigger_sanity_check_api_scans_sanity_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan */
        get: operations["get_scan_api_scans__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock Detail
         * @description Per-ticker deep-dive: latest stored recommendation + OHLC history.
         *
         *     ``history_days`` controls how many calendar days of price data come
         *     back. The frontend overlays entry/stop/target lines on this slice.
         */
        get: operations["get_stock_detail_api_stocks__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{ticker}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Ticker
         * @description Run the full analyzer chain on a single ticker on-demand.
         *
         *     Used by the web ticker-search bar so users can pull up a deep-dive on
         *     any ticker, not just ones present in the latest scan_run. Returns a
         *     ``ScanResultItem`` shaped identically to the rows produced by
         *     ``/api/scans`` — same composite score, sub-scores, signals, risk
         *     plan, and reasoning. ~3–8 s per call (price + fundamentals fetch
         *     dominate; both are cached).
         */
        post: operations["analyze_ticker_api_stocks__ticker__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtests */
        get: operations["list_backtests_api_backtests_get"];
        put?: never;
        /** Trigger Backtest */
        post: operations["trigger_backtest_api_backtests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest */
        get: operations["get_backtest_api_backtests__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Diagnostics */
        get: operations["list_diagnostics_api_diagnostics_get"];
        put?: never;
        /** Trigger Diagnostic */
        post: operations["trigger_diagnostic_api_diagnostics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Diagnostic */
        get: operations["get_diagnostic_api_diagnostics__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recommendations
         * @description Most recent paper-trading recommendations, newest first.
         *
         *     Left-joins paper_trades so each row carries the eventual outcome
         *     (target_hit / stop_hit / manual / other / open / pending / skipped)
         *     plus realized_pnl_pct when closed. A rec can spawn multiple trades
         *     (rare — partial fills, manual adds); we surface the most-recent
         *     closed trade.
         */
        get: operations["list_recommendations_api_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations/{rec_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recommendation */
        get: operations["get_recommendation_api_recommendations__rec_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Portfolio */
        get: operations["stream_portfolio_api_stream_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Heartbeat */
        get: operations["stream_heartbeat_api_stream_heartbeat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Prices
         * @description Live trade feed over SSE. Emits ``trade`` events
         *     ``{symbol, price, size, timestamp}`` for every Alpaca trade tick on the
         *     requested symbols; ``heartbeat`` events when idle.
         *
         *     All clients share one underlying Alpaca data-websocket connection — the
         *     free-tier quota is one socket per account, so the server multiplexes.
         */
        get: operations["stream_prices_api_stream_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/trade-updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Trade Updates
         * @description Account-wide Alpaca order events. Emits ``update`` per order state
         *     change (new, partial_fill, fill, canceled, stop_loss_filled,
         *     take_profit_filled, etc.). Frontend turns these into toasts.
         */
        get: operations["stream_trade_updates_api_stream_trade_updates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Scan
         * @description Run a scan and stream progress over SSE.
         *
         *     EventSource only supports GET, so all params come via query string.
         *     Emits these named events:
         *       - `progress`   {stage, n?}    pipeline stage transitions
         *       - `heartbeat`  {}             every ~1s when no progress event fires
         *       - `error`      {detail}       fatal failure; stream ends
         *       - `complete`   {run_id, n_results, strategy}   scan persisted
         *
         *     Disconnect cancels the worker task. The complete event includes the
         *     `run_id` so the client can `GET /api/scans/{run_id}` for full results.
         */
        get: operations["stream_scan_api_stream_scan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/regime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Regime
         * @description Current market-regime snapshot.
         *
         *     Reads SPY + VIX recent history (via the DataFetcher cache, so subsequent
         *     calls within market-hours TTL are free), computes SMA200 + recent VIX
         *     average, and returns a bull/bear/chop label plus the raw inputs the UI
         *     needs to render context.
         */
        get: operations["get_regime_api_market_regime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sectors
         * @description Per-sector momentum snapshot via the SPDR Select Sector ETFs.
         *
         *     Returns trailing 1-/5-/21-day total return for each sector ETF plus a
         *     50-day-SMA trend flag. UI renders this as a colored tile grid.
         */
        get: operations["get_sectors_api_market_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard
         * @description Aggregate per-strategy and cross-strategy picks.
         *
         *     For each strategy declared in ``config/strategies.yaml``, finds the
         *     most-recent ``scan_run`` and pulls the top BUY/STRONG BUY rows.
         *     Cross-strategy ``top_picks`` are the union of all strategies'
         *     BUYs, deduplicated by ticker (the highest-scoring strategy wins on
         *     collision) and capped at ``cross_strategy_top_n``.
         */
        get: operations["get_dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/briefing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Briefing */
        get: operations["get_briefing_api_dashboard_briefing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountSummary */
        AccountSummary: {
            /** Account Number */
            account_number: string;
            /** Status */
            status: string;
            /** Equity */
            equity: number;
            /** Cash */
            cash: number;
            /** Buying Power */
            buying_power: number;
            /** Portfolio Value */
            portfolio_value: number;
            /** Long Market Value */
            long_market_value: number;
            /** Pattern Day Trader */
            pattern_day_trader: boolean;
        };
        /**
         * ActionCounts
         * @description Set difference between today's picks and current paper positions.
         *     Mirrors the NEW BUY / KEEP / EXIT lists in the morning briefing
         *     markdown so the dashboard can headline the rebalance shape.
         */
        ActionCounts: {
            /** N New Buys */
            n_new_buys: number;
            /** N Keep */
            n_keep: number;
            /** N Exit */
            n_exit: number;
            /**
             * New Buy Tickers
             * @description Picks not currently held — fresh entries.
             */
            new_buy_tickers?: string[];
            /**
             * Keep Tickers
             * @description Picks already held — basket retains the position.
             */
            keep_tickers?: string[];
            /**
             * Exit Tickers
             * @description Currently-held tickers that dropped out of today's picks.
             */
            exit_tickers?: string[];
        };
        /** BacktestRequest */
        BacktestRequest: {
            /**
             * Strategy
             * @default swing_trading
             */
            strategy: string;
            /**
             * Universe
             * @default themes
             * @enum {string}
             */
            universe: "watchlist" | "portfolio" | "themes" | "tickers";
            /**
             * Tickers
             * @description Required when universe='tickers'. Ignored otherwise.
             */
            tickers?: string[] | null;
            /**
             * Years
             * @default 3
             */
            years: number;
            /** Min Score */
            min_score?: number | null;
            /**
             * Max Positions
             * @default 20
             */
            max_positions: number;
            /**
             * Position Pct
             * @default 0.1
             */
            position_pct: number;
            /**
             * Cash
             * @default 10000
             */
            cash: number;
            /**
             * Hold Days
             * @description Calendar days a position can hold before forced exit (triple-barrier time stop). None → resolve from the strategy's `time_stop_days` field, falling back to 90.
             */
            hold_days?: number | null;
            /**
             * Earnings Blackout
             * @default 3
             */
            earnings_blackout: number;
            /**
             * Accept Lookahead
             * @default false
             */
            accept_lookahead: boolean;
            /**
             * Oos Split
             * @default 0.3
             */
            oos_split: number;
            /**
             * Bootstrap Resamples
             * @default 0
             */
            bootstrap_resamples: number;
            /**
             * Commission
             * @default 0
             */
            commission: number;
            /**
             * Slippage Bps
             * @default 5
             */
            slippage_bps: number;
            /**
             * Regulatory Bps
             * @default 3
             */
            regulatory_bps: number;
            /**
             * Vol Target Risk
             * @default 0
             */
            vol_target_risk: number;
            /**
             * Fresh
             * @default false
             */
            fresh: boolean;
        };
        /** BacktestResponse */
        BacktestResponse: {
            /** Id */
            id: number;
            /** Strategy */
            strategy: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** BacktestSummary */
        BacktestSummary: {
            /** Id */
            id: number;
            /** Strategy */
            strategy: string;
            /** Universe Label */
            universe_label: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** N Trades */
            n_trades?: number | null;
            /** Oos Sharpe */
            oos_sharpe?: number | null;
            /** Oos Total Return Pct */
            oos_total_return_pct?: number | null;
            /** Oos Max Drawdown Pct */
            oos_max_drawdown_pct?: number | null;
        };
        /** BriefingResponse */
        BriefingResponse: {
            /**
             * Picks Date
             * @description Date of the picks file underlying this briefing. Null when no picks have been generated yet for today.
             */
            picks_date?: string | null;
            /**
             * Gate Status
             * @description Overall pre-trade gate verdict. 'fail' means refuse the rebalance; 'warn' means proceed with caution; 'ok' means drift checks clean; 'no_picks' means today's picks file is missing (briefing degrades to position alerts only).
             * @enum {string}
             */
            gate_status: "ok" | "warn" | "fail" | "no_picks";
            /**
             * Gate Message
             * @description One-line summary of why the gate failed/warned, or 'all drift checks passed' on OK.
             */
            gate_message: string;
            /**
             * Recommendation
             * @description Single sentence: what the system thinks the operator should do this morning.
             */
            recommendation: string;
            /** Drift Checks */
            drift_checks?: components["schemas"]["DriftCheckOut"][];
            /** Factor Coverage */
            factor_coverage?: components["schemas"]["FactorCoverage"][];
            /**
             * N Picks
             * @default 0
             */
            n_picks: number;
            /** Position Alerts */
            position_alerts?: components["schemas"]["PositionAlert"][];
            /**
             * N Stops Hit
             * @default 0
             */
            n_stops_hit: number;
            /**
             * N Targets Hit
             * @default 0
             */
            n_targets_hit: number;
            /**
             * N Near Stop
             * @default 0
             */
            n_near_stop: number;
            /**
             * N Positions
             * @default 0
             */
            n_positions: number;
            /**
             * Top Picks
             * @description Top-N picks by composite rank, projected for the dashboard hero card. Empty when no picks file exists for the date.
             */
            top_picks?: components["schemas"]["TopPick"][];
            /** @description NEW BUY / KEEP / EXIT counts from set-diff of today's picks vs current paper positions. Null when picks or positions couldn't be resolved. */
            action_counts?: components["schemas"]["ActionCounts"] | null;
            /**
             * Paper Equity Usd
             * @description Live paper-account equity. Null when Alpaca is unreachable.
             */
            paper_equity_usd?: number | null;
            /**
             * Unrealized Pl Usd
             * @description Sum of unrealized P&L across held positions.
             */
            unrealized_pl_usd?: number | null;
            /**
             * Unrealized Pl Pct
             * @description unrealized_pl_usd / paper_equity_usd * 100.
             */
            unrealized_pl_pct?: number | null;
            /**
             * Picks Generated At
             * @description Filesystem mtime of the picks JSON. Surfaces pipeline freshness without an extra API call.
             */
            picks_generated_at?: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /**
         * BuySignal
         * @description One ticker with a current BUY+ signal from the latest scan per strategy.
         *
         *     Deduped across strategies: each ticker appears once, attributed to the
         *     strategy that produced its highest composite_score. ``consensus_count``
         *     counts how many strategies' latest runs all flagged this ticker as
         *     BUY+ — high consensus = stronger conviction.
         */
        BuySignal: {
            /** Ticker */
            ticker: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Sector
             * @default Unknown
             */
            sector: string;
            /**
             * Industry
             * @default Unknown
             */
            industry: string;
            /** Market Cap */
            market_cap?: number | null;
            /**
             * Action
             * @enum {string}
             */
            action: "STRONG BUY" | "BUY";
            /** Composite Score */
            composite_score: number;
            /** Confidence */
            confidence: string;
            /** Strategy */
            strategy: string;
            /**
             * Scan Timestamp
             * Format: date-time
             */
            scan_timestamp: string;
            /** Run Id */
            run_id: string;
            /** Consensus Count */
            consensus_count: number;
            /** Consensus Strategies */
            consensus_strategies?: string[];
            /** Sub Scores */
            sub_scores?: {
                [key: string]: number;
            };
            /** Earnings Announcement Ts */
            earnings_announcement_ts?: number | null;
            /** Earnings Call Ts */
            earnings_call_ts?: number | null;
            sanity_check?: components["schemas"]["SanityCheck"] | null;
        };
        /**
         * DashboardPick
         * @description One pick row — flat enough to render in a table without a per-row
         *     /api/stocks roundtrip. Mirrors a subset of ``ScanResultItem``.
         */
        DashboardPick: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string;
            /**
             * Action
             * @enum {string}
             */
            action: "STRONG BUY" | "BUY" | "HOLD" | "SELL" | "STRONG SELL";
            /** Composite Score */
            composite_score: number;
            /** Strategy */
            strategy: string;
            /** Entry Price */
            entry_price?: number | null;
            /** Stop Loss */
            stop_loss?: number | null;
            /** Take Profit */
            take_profit?: number | null;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /**
             * Top Picks
             * @description Cross-strategy top BUY/STRONG BUY picks, ranked by composite_score. Deduplicated by ticker — when a ticker scored in multiple strategies, keeps the highest score.
             */
            top_picks?: components["schemas"]["DashboardPick"][];
            /** Strategies */
            strategies?: components["schemas"]["StrategyCard"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** DiagnosticRequest */
        DiagnosticRequest: {
            /**
             * Strategy
             * @default swing_trading
             */
            strategy: string;
            /**
             * Universe
             * @default themes
             * @enum {string}
             */
            universe: "watchlist" | "portfolio" | "themes" | "tickers";
            /** Tickers */
            tickers?: string[] | null;
            /**
             * Years
             * @default 2
             */
            years: number;
            /**
             * Factor
             * @default composite
             * @enum {string}
             */
            factor: "composite" | "technical" | "fundamental" | "pattern" | "statistical" | "trend" | "alpha158";
            /**
             * Quantiles
             * @default 5
             */
            quantiles: number;
            /**
             * Periods
             * @description Forward-return horizons in trading days.
             */
            periods?: number[];
            /**
             * Accept Lookahead
             * @default false
             */
            accept_lookahead: boolean;
            /**
             * Fresh
             * @default false
             */
            fresh: boolean;
        };
        /** DiagnosticResponse */
        DiagnosticResponse: {
            /** Id */
            id: number;
            /** Factor */
            factor: string;
            /** Universe Label */
            universe_label: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Quantiles */
            quantiles: number;
            /** N Observations */
            n_observations: number;
            /** Ic Mean */
            ic_mean: {
                [key: string]: number;
            };
            /** Ic Std */
            ic_std: {
                [key: string]: number;
            };
            /** Ic Ir */
            ic_ir: {
                [key: string]: number;
            };
            /** Top Minus Bottom Pct */
            top_minus_bottom_pct: {
                [key: string]: number;
            };
            /**
             * Verdict
             * @default
             */
            verdict: string;
        };
        /** DiagnosticSummary */
        DiagnosticSummary: {
            /** Id */
            id: number;
            /** Factor */
            factor: string;
            /** Universe Label */
            universe_label: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** N Observations */
            n_observations: number;
            /**
             * Verdict
             * @default
             */
            verdict: string;
        };
        /**
         * DriftCheckOut
         * @description One drift-detector check, flattened for the FE.
         */
        DriftCheckOut: {
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warn" | "fail";
            /** Message */
            message: string;
        };
        /** EquityPoint */
        EquityPoint: {
            /** Timestamp */
            timestamp: number;
            /** Equity */
            equity: number;
            /** Profit Loss */
            profit_loss: number;
            /** Profit Loss Pct */
            profit_loss_pct?: number | null;
        };
        /**
         * FactorCoverage
         * @description How many of today's picks have a non-null rank for one factor.
         *     A drop vs the rolling baseline is the canary for an ingest break.
         */
        FactorCoverage: {
            /** Factor */
            factor: string;
            /** Covered */
            covered: number;
            /** Total */
            total: number;
            /** Pct */
            pct: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warn" | "fail";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MarketRegime
         * @description Snapshot of the broader-market regime indicators a swing trader cares
         *     about. Classification is intentionally crude — the user makes the call;
         *     this just surfaces the inputs.
         */
        MarketRegime: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Label
             * @enum {string}
             */
            label: "bull" | "bear" | "chop" | "unknown";
            /** Spy Price */
            spy_price?: number | null;
            /** Spy Sma200 */
            spy_sma200?: number | null;
            /** Spy Above Sma200 */
            spy_above_sma200?: boolean | null;
            /** Spy Pct From Sma200 */
            spy_pct_from_sma200?: number | null;
            /** Vix Level */
            vix_level?: number | null;
            /** Vix Avg 20D */
            vix_avg_20d?: number | null;
            /** Notes */
            notes?: string[];
        };
        /**
         * OHLCBar
         * @description One trading day for the chart. Volume is optional — most chart
         *     libraries don't need it for the entry/stop/target overlay view.
         */
        OHLCBar: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume?: number | null;
        };
        /** PaperRecommendationItem */
        PaperRecommendationItem: {
            /** Id */
            id: number;
            /** Ticker */
            ticker: string;
            /** Strategy */
            strategy: string;
            /**
             * Scan Timestamp
             * Format: date-time
             */
            scan_timestamp: string;
            /** Composite Score */
            composite_score: number;
            /**
             * Action
             * @enum {string}
             */
            action: "STRONG BUY" | "BUY" | "HOLD" | "SELL" | "STRONG SELL";
            /** Sub Scores */
            sub_scores?: {
                [key: string]: number;
            };
            /** Entry Price */
            entry_price?: number | null;
            /** Stop Loss */
            stop_loss?: number | null;
            /** Take Profit */
            take_profit?: number | null;
            /** Sector */
            sector?: string | null;
            /** Earnings In Days */
            earnings_in_days?: number | null;
            /**
             * Submitted
             * @default false
             */
            submitted: boolean;
            /** Skip Reason */
            skip_reason?: string | null;
            /** Outcome */
            outcome?: ("skipped" | "pending" | "open" | "target_hit" | "stop_hit" | "manual" | "other") | null;
            /** Realized Pnl Pct */
            realized_pnl_pct?: number | null;
        };
        /** PortfolioHistory */
        PortfolioHistory: {
            /** Period */
            period: string;
            /** Timeframe */
            timeframe: string;
            /** Base Value */
            base_value?: number | null;
            /** Points */
            points?: components["schemas"]["EquityPoint"][];
        };
        /** PortfolioStatus */
        PortfolioStatus: {
            account: components["schemas"]["AccountSummary"];
            /** Positions */
            positions: components["schemas"]["Position"][];
            /** N Positions */
            n_positions: number;
        };
        /** Position */
        Position: {
            /** Ticker */
            ticker: string;
            /** Shares */
            shares: number;
            /** Avg Price */
            avg_price: number;
            /** Current Price */
            current_price?: number | null;
            /** Market Value */
            market_value?: number | null;
            /**
             * Unrealized Pnl
             * @default 0
             */
            unrealized_pnl: number;
            /**
             * Unrealized Pnl Pct
             * @default 0
             */
            unrealized_pnl_pct: number;
        };
        /**
         * PositionAlert
         * @description A held position that hit a stop, target, or is within 2% of either.
         */
        PositionAlert: {
            /** Ticker */
            ticker: string;
            /**
             * Status
             * @enum {string}
             */
            status: "STOP_HIT" | "TARGET_HIT" | "NEAR_STOP" | "NEAR_TARGET";
            /** Current Price */
            current_price: number;
            /** Avg Entry */
            avg_entry: number;
            /** Stop */
            stop: number;
            /** Target */
            target: number;
            /** Shares */
            shares: number;
            /** Pl Pct */
            pl_pct: number;
            /**
             * Source
             * @enum {string}
             */
            source: "strategy" | "fallback_8pct";
        };
        /**
         * PositionSizing
         * @description Per-trade position sizing output.
         */
        PositionSizing: {
            /**
             * Method
             * @constant
             */
            method: "fixed_fractional";
            /** Portfolio Value */
            portfolio_value: number;
            /** Recommended Shares */
            recommended_shares: number;
            /** Dollar Amount */
            dollar_amount: number;
            /** Pct Of Portfolio */
            pct_of_portfolio: number;
            /** Risk Per Trade */
            risk_per_trade?: number | null;
            /** Risk Pct */
            risk_pct?: number | null;
            /** Risk Budget Pct */
            risk_budget_pct?: number | null;
        };
        /**
         * RiskManagement
         * @description Full risk envelope. All children are Optional so a recommendation
         *     can omit individual blocks (e.g. ``risk_management={}`` when the
         *     refusal gates fired) without violating the schema.
         */
        RiskManagement: {
            /** Current Price */
            current_price?: number | null;
            /** Entry Price */
            entry_price?: number | null;
            stop_loss?: components["schemas"]["StopLoss"] | null;
            take_profit?: components["schemas"]["TakeProfit"] | null;
            time_stop?: components["schemas"]["TimeStop"] | null;
            position?: components["schemas"]["PositionSizing"] | null;
            /** Risk Reward Ratio */
            risk_reward_ratio?: number | null;
        };
        /**
         * SanityCheck
         * @description One pre-trade sanity-check result. Renders as a badge on the
         *     /buy-signals row.
         *
         *     A REJECT means the LLM identified an obvious one-off catalyst that
         *     explains the recent move and the BUY is likely to mean-revert. The
         *     FE's "Hide rejected" filter operates on this field.
         *
         *     ``model_used`` and ``mocked`` exist so we can audit which checks
         *     came from a real LLM call vs the placeholder mock. Real-money
         *     constraint: every check that fed a decision must be auditable.
         */
        SanityCheck: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "OK" | "CAUTION" | "REJECT";
            /** Reason */
            reason: string;
            /** Catalysts Found */
            catalysts_found?: string[];
            /** Confidence */
            confidence: number;
            /**
             * Model Used
             * @default mock
             */
            model_used: string;
            /**
             * Mocked
             * @default false
             */
            mocked: boolean;
            /** Checked At */
            checked_at?: string | null;
        };
        /**
         * SanityCheckTriggerRequest
         * @description Body for POST /api/scans/sanity-check.
         *
         *     Runs the sanity-check pass over the current BuySignal set and upserts
         *     one row per (ticker, run_id). Returns the refreshed list with
         *     ``sanity_check`` populated.
         */
        SanityCheckTriggerRequest: {
            /**
             * Strong Only
             * @description When true, runs the check only on STRONG BUY rows. Default covers both STRONG BUY and BUY.
             * @default false
             */
            strong_only: boolean;
            /**
             * Mode
             * @description 'auto' uses the live LLM when ANTHROPIC_API_KEY is present and falls back to the mock otherwise. 'mock' forces the rule-based mock (no API key needed, no LLM cost). 'live' forces the real path and raises if the key is missing.
             * @default auto
             * @enum {string}
             */
            mode: "auto" | "mock" | "live";
            /**
             * Force Refresh
             * @description When true, re-runs the check even if a cached result exists for this (ticker, run_id). Default uses cache.
             * @default false
             */
            force_refresh: boolean;
        };
        /** ScanRequest */
        ScanRequest: {
            /**
             * Strategy
             * @default swing_trading
             */
            strategy: string;
            /** Budget */
            budget?: number | null;
            /**
             * Universe
             * @description Ticker universe. 'themes' (default) uses the configured theme set (~67 tickers, fast). 'russell_1000' scans the full Russell-1000 holdings (~1000 tickers, slow — ~15-30min with live_signals=True). 'value_cohort' / 'watchlist' use the configured lists. When omitted, falls back to 'themes' OR a theme/sector filter if provided.
             */
            universe?: ("themes" | "russell_1000" | "value_cohort" | "watchlist") | null;
            /** Theme */
            theme?: string | null;
            /** Sector */
            sector?: string | null;
            /** Top */
            top?: number | null;
            /**
             * Fresh
             * @description Bypass cache, fetch live data
             * @default false
             */
            fresh: boolean;
            /**
             * Live Signals
             * @description Fetch yfinance-backed analyst_revisions + options_skew. Disable on large universes (russell_1000) for speed.
             * @default true
             */
            live_signals: boolean;
        };
        /** ScanResponse */
        ScanResponse: {
            /** Run Id */
            run_id: string;
            /** Strategy */
            strategy: string;
            /**
             * Scan Timestamp
             * Format: date-time
             */
            scan_timestamp: string;
            /** N Candidates */
            n_candidates: number;
            /** N Results */
            n_results: number;
            /** Results */
            results: components["schemas"]["ScanResultItem"][];
        };
        /**
         * ScanResultItem
         * @description One recommendation row in a scan response. Permissive shape — accepts
         *     the existing recommender dict; web layer narrows what it renders.
         *
         *     Integrity fields (``score_valid``, ``error_count``, ``error_slots``,
         *     ``analyzer_status``, ``instrument_warning``, ``insufficient_history``)
         *     are surfaced so the FE can render a Data-Quality warning when the
         *     composite was built from a degraded analyzer chain, a leveraged /
         *     inverse ETF, or a ticker with too little history. The recommender
         *     already forces ``action="HOLD"``/``confidence="None"`` in those
         *     cases — these fields tell the operator WHY.
         */
        ScanResultItem: {
            /** Ticker */
            ticker: string;
            /**
             * Action
             * @enum {string}
             */
            action: "STRONG BUY" | "BUY" | "HOLD" | "SELL" | "STRONG SELL";
            /** Composite Score */
            composite_score: number;
            /** Confidence */
            confidence: string;
            /** Sub Scores */
            sub_scores?: {
                [key: string]: number;
            };
            /** Reasoning */
            reasoning?: string[];
            /**
             * Bullish Signals
             * @default 0
             */
            bullish_signals: number;
            /**
             * Bearish Signals
             * @default 0
             */
            bearish_signals: number;
            /** Breakdown */
            breakdown?: {
                [key: string]: unknown;
            }[];
            risk_management?: components["schemas"]["RiskManagement"];
            /**
             * Sector
             * @default Unknown
             */
            sector: string;
            /**
             * Industry
             * @default Unknown
             */
            industry: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Market Cap */
            market_cap?: number | null;
            /**
             * Score Valid
             * @default true
             */
            score_valid: boolean;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
            /** Error Slots */
            error_slots?: string[];
            /** Analyzer Status */
            analyzer_status?: {
                [key: string]: string;
            };
            /** Instrument Warning */
            instrument_warning?: ("leveraged_or_inverse_etf" | "non_stock_instrument") | null;
            /** Instrument Warning Reason */
            instrument_warning_reason?: string | null;
            /**
             * Insufficient History
             * @default false
             */
            insufficient_history: boolean;
            /** History Bars Available */
            history_bars_available?: number | null;
            /** History Bars Required */
            history_bars_required?: number | null;
            /** Strategy Filter Failed */
            strategy_filter_failed?: "missing_dividend" | null;
            /** Strategy Filter Reason */
            strategy_filter_reason?: string | null;
            /** Earnings Announcement Ts */
            earnings_announcement_ts?: number | null;
            /** Earnings Call Ts */
            earnings_call_ts?: number | null;
            /** Earnings Window Start */
            earnings_window_start?: number | null;
            /** Earnings Window End */
            earnings_window_end?: number | null;
        };
        /**
         * ScanSummary
         * @description Lighter representation for the GET /api/scans list view.
         */
        ScanSummary: {
            /** Run Id */
            run_id: string;
            /** Strategy */
            strategy: string;
            /**
             * Scan Timestamp
             * Format: date-time
             */
            scan_timestamp: string;
            /** N Candidates */
            n_candidates: number;
            /** Top Ticker */
            top_ticker?: string | null;
            /** Top Score */
            top_score?: number | null;
        };
        /** SectorMetric */
        SectorMetric: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Last Close */
            last_close?: number | null;
            /** Sma50 */
            sma50?: number | null;
            /** Above Sma50 */
            above_sma50?: boolean | null;
            /** Return 1D Pct */
            return_1d_pct?: number | null;
            /** Return 5D Pct */
            return_5d_pct?: number | null;
            /** Return 21D Pct */
            return_21d_pct?: number | null;
            /** History 30D Pct */
            history_30d_pct?: number[];
        };
        /** SectorsResponse */
        SectorsResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Sectors */
            sectors?: components["schemas"]["SectorMetric"][];
        };
        /** StockDetail */
        StockDetail: {
            /** Ticker */
            ticker: string;
            /** @description Engine's most recent recommendation row for this ticker, or null if it has never appeared in a stored scan_run. */
            latest_recommendation?: components["schemas"]["ScanResultItem"] | null;
            /** Scan Run Id */
            scan_run_id?: string | null;
            /** Scan Strategy */
            scan_strategy?: string | null;
            /** Scan Timestamp */
            scan_timestamp?: string | null;
            /**
             * History
             * @description Recent OHLC bars for charting. Window is controlled by the endpoint's `history_days` query param (default 120).
             */
            history?: components["schemas"]["OHLCBar"][];
        };
        /**
         * StopLoss
         * @description Stop-loss level + provenance. ``method`` is what the recommender
         *     actually used (fallbacks rewrite it) — read the recommender code
         *     if you're tempted to assume the requested method always survives.
         */
        StopLoss: {
            /**
             * Method
             * @enum {string}
             */
            method: "atr" | "percentage" | "support";
            /** Price */
            price: number;
            /** Pct From Current */
            pct_from_current: number;
            /** Detail */
            detail: string;
            /** Atr Multiplier */
            atr_multiplier?: number | null;
        };
        /**
         * StrategyCard
         * @description Per-strategy summary tile.
         */
        StrategyCard: {
            /** Strategy */
            strategy: string;
            /** Description */
            description: string;
            /** Horizon */
            horizon: string;
            /** Last Scan At */
            last_scan_at?: string | null;
            /** Last Scan Run Id */
            last_scan_run_id?: string | null;
            /** Last Scan Universe */
            last_scan_universe?: string | null;
            /**
             * N Buys
             * @default 0
             */
            n_buys: number;
            /** Top Picks */
            top_picks?: components["schemas"]["DashboardPick"][];
            /** Oos Sharpe */
            oos_sharpe?: number | null;
            /** Full Sharpe */
            full_sharpe?: number | null;
            /** Win Rate Pct */
            win_rate_pct?: number | null;
            /** Sweep Universe */
            sweep_universe?: string | null;
        };
        /**
         * TakeProfit
         * @description Take-profit level + provenance.
         *
         *     Note the asymmetry with StopLoss: when method='resistance' fails
         *     (no resistance ≥ min R/R), method is rewritten to 'risk_reward',
         *     matching the StopLoss percentage fallback pattern. The FE should
         *     branch on the FINAL method, not what was requested.
         */
        TakeProfit: {
            /**
             * Method
             * @enum {string}
             */
            method: "risk_reward" | "atr" | "resistance";
            /** Price */
            price: number;
            /** Pct From Current */
            pct_from_current: number;
            /** Detail */
            detail: string;
            /** Atr Multiplier */
            atr_multiplier?: number | null;
        };
        /**
         * TimeStop
         * @description Triple-barrier time stop — forced exit N calendar days after entry.
         */
        TimeStop: {
            /**
             * Method
             * @constant
             */
            method: "calendar";
            /** Days */
            days: number;
            /** Exit Date */
            exit_date: string;
            /** Detail */
            detail: string;
        };
        /**
         * TopPick
         * @description Compact per-pick row for the dashboard hero card. Mirrors the
         *     fields the per-stock rationale chips need without dragging the full
         *     factor-picks JSON into the briefing response.
         */
        TopPick: {
            /** Rank */
            rank: number;
            /** Ticker */
            ticker: string;
            /** Z Score */
            z_score?: number | null;
            /** Sector */
            sector?: string | null;
            /** Mom Rank */
            mom_rank?: number | null;
            /** Qual Rank */
            qual_rank?: number | null;
            /** Val Rank */
            val_rank?: number | null;
            /** Pead Rank */
            pead_rank?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_portfolio_api_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioStatus"];
                };
            };
        };
    };
    get_positions_api_portfolio_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Position"][];
                };
            };
        };
    };
    get_account_api_portfolio_account_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"];
                };
            };
        };
    };
    get_history_api_portfolio_history_get: {
        parameters: {
            query?: {
                period?: "1D" | "1W" | "1M" | "3M" | "6M" | "1A";
                timeframe?: "1Min" | "5Min" | "15Min" | "1H" | "1D";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scans_api_scans_get: {
        parameters: {
            query?: {
                strategy?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_scan_api_scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_buys_api_scans_latest_buys_get: {
        parameters: {
            query?: {
                /** @description When true, returns only STRONG BUY signals (filters out plain BUY). */
                strong_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuySignal"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    factor_picks_api_scans_factor_picks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuySignal"][];
                };
            };
        };
    };
    trigger_sanity_check_api_scans_sanity_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SanityCheckTriggerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuySignal"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_scans__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_detail_api_stocks__ticker__get: {
        parameters: {
            query?: {
                history_days?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_ticker_api_stocks__ticker__analyze_post: {
        parameters: {
            query?: {
                strategy?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResultItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backtests_api_backtests_get: {
        parameters: {
            query?: {
                strategy?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_backtest_api_backtests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_api_backtests__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_diagnostics_api_diagnostics_get: {
        parameters: {
            query?: {
                factor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_diagnostic_api_diagnostics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnosticRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diagnostic_api_diagnostics__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recommendations_api_recommendations_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                strategy?: string | null;
                submitted_only?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperRecommendationItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendation_api_recommendations__rec_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rec_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperRecommendationItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_portfolio_api_stream_portfolio_get: {
        parameters: {
            query?: {
                poll_seconds?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_heartbeat_api_stream_heartbeat_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stream_prices_api_stream_prices_get: {
        parameters: {
            query: {
                /** @description Comma-separated symbols (e.g. AAPL,MSFT,TSLA) */
                symbols: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_trade_updates_api_stream_trade_updates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stream_scan_api_stream_scan_get: {
        parameters: {
            query?: {
                strategy?: string;
                budget?: number | null;
                universe?: string | null;
                theme?: string | null;
                sector?: string | null;
                top?: number | null;
                fresh?: boolean;
                live_signals?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_regime_api_market_regime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketRegime"];
                };
            };
        };
    };
    get_sectors_api_market_sectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorsResponse"];
                };
            };
        };
    };
    get_dashboard_api_dashboard_get: {
        parameters: {
            query?: {
                top_n_per_strategy?: number;
                cross_strategy_top_n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_briefing_api_dashboard_briefing_get: {
        parameters: {
            query?: {
                /** @description YYYY-MM-DD. Defaults to today's UTC date. */
                picks_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
