/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Cheap liveness check — process is up and serving.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness check — verifies Postgres + Redis are reachable.
         *
         *     Returns 200 only when both adapters round-trip. Use this from a deploy
         *     health probe; use /health for fast process-alive checks.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description Live snapshot: account fields + current positions.
         */
        get: operations["get_portfolio_api_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Positions */
        get: operations["get_positions_api_portfolio_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account */
        get: operations["get_account_api_portfolio_account_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scans
         * @description Most recent scan runs, newest first.
         */
        get: operations["list_scans_api_scans_get"];
        put?: never;
        /**
         * Trigger Scan
         * @description Run a synchronous scan and persist the result.
         *
         *     Synchronous from the caller's perspective — blocks until the scan
         *     completes. Heavy compute runs in a worker thread so the event loop stays
         *     responsive. Phase 1.7 adds /api/stream/scan-progress for live updates.
         */
        post: operations["trigger_scan_api_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan */
        get: operations["get_scan_api_scans__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stocks/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock Detail
         * @description Per-ticker deep-dive: latest stored recommendation + OHLC history.
         *
         *     ``history_days`` controls how many calendar days of price data come
         *     back. The frontend overlays entry/stop/target lines on this slice.
         */
        get: operations["get_stock_detail_api_stocks__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtests */
        get: operations["list_backtests_api_backtests_get"];
        put?: never;
        /** Trigger Backtest */
        post: operations["trigger_backtest_api_backtests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest */
        get: operations["get_backtest_api_backtests__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Diagnostics */
        get: operations["list_diagnostics_api_diagnostics_get"];
        put?: never;
        /** Trigger Diagnostic */
        post: operations["trigger_diagnostic_api_diagnostics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Diagnostic */
        get: operations["get_diagnostic_api_diagnostics__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recommendations
         * @description Most recent paper-trading recommendations, newest first.
         */
        get: operations["list_recommendations_api_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations/{rec_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recommendation */
        get: operations["get_recommendation_api_recommendations__rec_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Portfolio */
        get: operations["stream_portfolio_api_stream_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Heartbeat */
        get: operations["stream_heartbeat_api_stream_heartbeat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Prices
         * @description Live trade feed over SSE. Emits ``trade`` events
         *     ``{symbol, price, size, timestamp}`` for every Alpaca trade tick on the
         *     requested symbols; ``heartbeat`` events when idle.
         *
         *     All clients share one underlying Alpaca data-websocket connection — the
         *     free-tier quota is one socket per account, so the server multiplexes.
         */
        get: operations["stream_prices_api_stream_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/trade-updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Trade Updates
         * @description Account-wide Alpaca order events. Emits ``update`` per order state
         *     change (new, partial_fill, fill, canceled, stop_loss_filled,
         *     take_profit_filled, etc.). Frontend turns these into toasts.
         */
        get: operations["stream_trade_updates_api_stream_trade_updates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Scan
         * @description Run a scan and stream progress over SSE.
         *
         *     EventSource only supports GET, so all params come via query string.
         *     Emits these named events:
         *       - `progress`   {stage, n?}    pipeline stage transitions
         *       - `heartbeat`  {}             every ~1s when no progress event fires
         *       - `error`      {detail}       fatal failure; stream ends
         *       - `complete`   {run_id, n_results, strategy}   scan persisted
         *
         *     Disconnect cancels the worker task. The complete event includes the
         *     `run_id` so the client can `GET /api/scans/{run_id}` for full results.
         */
        get: operations["stream_scan_api_stream_scan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/regime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Regime
         * @description Current market-regime snapshot.
         *
         *     Reads SPY + VIX recent history (via the DataFetcher cache, so subsequent
         *     calls within market-hours TTL are free), computes SMA200 + recent VIX
         *     average, and returns a bull/bear/chop label plus the raw inputs the UI
         *     needs to render context.
         */
        get: operations["get_regime_api_market_regime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sectors
         * @description Per-sector momentum snapshot via the SPDR Select Sector ETFs.
         *
         *     Returns trailing 1-/5-/21-day total return for each sector ETF plus a
         *     50-day-SMA trend flag. UI renders this as a colored tile grid.
         */
        get: operations["get_sectors_api_market_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Score Calibration
         * @description Score-vs-realized-return calibration.
         *
         *     Buckets every closed paper trade by its composite_score band and reports
         *     n_trades + avg / median pnl_pct + win_rate per bucket. The goal: confirm
         *     that higher composite scores really do produce higher realized returns
         *     — and surface drift early if they stop doing so.
         */
        get: operations["score_calibration_api_analytics_calibration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trades
         * @description Closed paper trades, newest exit first. Filter by ticker, score
         *     floor, or whether the row already has notes.
         */
        get: operations["list_trades_api_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades/{trade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Trade Notes
         * @description Replace the notes field. ``null`` clears the entry.
         */
        patch: operations["update_trade_notes_api_trades__trade_id__patch"];
        trace?: never;
    };
    "/api/ml/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ml Models
         * @description List registered model versions + drift status for the latest of each name.
         *
         *     Filter to a single ``model_name`` to see its history. Without a filter,
         *     you get the full registry (newest first) plus a "latest per name" view
         *     that mirrors what the ensemble would use right now.
         */
        get: operations["list_ml_models_api_ml_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Kick off one synchronous research run. Returns the completed
         *     (or failed / budget_exceeded) run row inline.
         *
         *     The orchestrator never raises on tool failures — those are threaded
         *     back into the transcript. We do raise 503 if the ANTHROPIC_API_KEY
         *     is missing so the UI can prompt for setup.
         */
        post: operations["ask_api_research_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/ask/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Stream
         * @description Stream the agent's mid-run thoughts over SSE.
         *
         *     Events (named):
         *       - ``started``         {run_id, question}
         *       - ``turn_start``      {turn}
         *       - ``assistant_text``  {turn, text}   any prose the model emits
         *                                             alongside a tool call
         *       - ``tool_call``       {turn, tool, input}
         *       - ``tool_result``     {turn, tool, is_error, summary}
         *       - ``usage``           {turn, input_tokens, output_tokens, cost_usd}
         *       - ``final_answer``    {text}
         *       - ``complete``        {run_id, status}
         *       - ``error``           {detail, kind}
         *
         *     Client disconnects cancel the worker task — the partial run row
         *     stays in the DB with whatever transcript it had at the time.
         */
        post: operations["ask_stream_api_research_ask_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_research_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_research_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Notifications
         * @description Recent filings the background monitor surfaced. Newest first.
         */
        get: operations["list_notifications_api_research_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/notifications/{notification_id}/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summarize Notification
         * @description Kick off an agent run to summarize one filing.
         *
         *     Uses ``search_filings`` under the hood — the filing's chunks are
         *     already in the corpus (the monitor ingested them at detection
         *     time). Result is cached on ``filing_notifications.summary`` so
         *     repeat clicks return instantly.
         */
        post: operations["summarize_notification_api_research_notifications__notification_id__summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/notifications/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Notifications
         * @description SSE channel: live filing notifications. Events are named
         *     ``notification`` with the persisted row's slim shape.
         *
         *     No ``status`` event on the channel — the EventMonitor is either
         *     running (background task alive) or not (env-disabled); the API
         *     surface for that lives at ``GET /api/research/monitor/status``.
         */
        get: operations["stream_notifications_api_research_notifications_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/monitor/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monitor Status
         * @description Lightweight liveness probe for the /research/feed page header.
         */
        get: operations["monitor_status_api_research_monitor_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountSummary */
        AccountSummary: {
            /** Account Number */
            account_number: string;
            /** Status */
            status: string;
            /** Equity */
            equity: number;
            /** Cash */
            cash: number;
            /** Buying Power */
            buying_power: number;
            /** Portfolio Value */
            portfolio_value: number;
            /** Long Market Value */
            long_market_value: number;
            /** Pattern Day Trader */
            pattern_day_trader: boolean;
        };
        /** BacktestRequest */
        BacktestRequest: {
            /**
             * Strategy
             * @default swing_trading
             */
            strategy: string;
            /**
             * Universe
             * @default themes
             * @enum {string}
             */
            universe: "watchlist" | "portfolio" | "themes" | "tickers";
            /**
             * Tickers
             * @description Required when universe='tickers'. Ignored otherwise.
             */
            tickers?: string[] | null;
            /**
             * Years
             * @default 3
             */
            years: number;
            /** Min Score */
            min_score?: number | null;
            /**
             * Max Positions
             * @default 20
             */
            max_positions: number;
            /**
             * Position Pct
             * @default 0.1
             */
            position_pct: number;
            /**
             * Cash
             * @default 10000
             */
            cash: number;
            /**
             * Hold Days
             * @default 90
             */
            hold_days: number;
            /**
             * Earnings Blackout
             * @default 3
             */
            earnings_blackout: number;
            /**
             * Accept Lookahead
             * @default false
             */
            accept_lookahead: boolean;
            /**
             * Oos Split
             * @default 0.3
             */
            oos_split: number;
            /**
             * Bootstrap Resamples
             * @default 0
             */
            bootstrap_resamples: number;
            /**
             * Commission
             * @default 0
             */
            commission: number;
            /**
             * Slippage Bps
             * @default 5
             */
            slippage_bps: number;
            /**
             * Regulatory Bps
             * @default 3
             */
            regulatory_bps: number;
            /**
             * Vol Target Risk
             * @default 0
             */
            vol_target_risk: number;
            /**
             * Fresh
             * @default false
             */
            fresh: boolean;
        };
        /** BacktestResponse */
        BacktestResponse: {
            /** Id */
            id: number;
            /** Strategy */
            strategy: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** BacktestSummary */
        BacktestSummary: {
            /** Id */
            id: number;
            /** Strategy */
            strategy: string;
            /** Universe Label */
            universe_label: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** N Trades */
            n_trades?: number | null;
            /** Oos Sharpe */
            oos_sharpe?: number | null;
            /** Oos Total Return Pct */
            oos_total_return_pct?: number | null;
            /** Oos Max Drawdown Pct */
            oos_max_drawdown_pct?: number | null;
        };
        /** CalibrationBucket */
        CalibrationBucket: {
            /** Label */
            label: string;
            /** Lower */
            lower: number;
            /** Upper */
            upper: number;
            /** N Trades */
            n_trades: number;
            /** Avg Pnl Pct */
            avg_pnl_pct?: number | null;
            /** Median Pnl Pct */
            median_pnl_pct?: number | null;
            /** Win Rate */
            win_rate?: number | null;
        };
        /** DiagnosticRequest */
        DiagnosticRequest: {
            /**
             * Strategy
             * @default swing_trading
             */
            strategy: string;
            /**
             * Universe
             * @default themes
             * @enum {string}
             */
            universe: "watchlist" | "portfolio" | "themes" | "tickers";
            /** Tickers */
            tickers?: string[] | null;
            /**
             * Years
             * @default 2
             */
            years: number;
            /**
             * Factor
             * @default composite
             * @enum {string}
             */
            factor: "composite" | "technical" | "fundamental" | "pattern" | "statistical" | "trend" | "alpha158";
            /**
             * Quantiles
             * @default 5
             */
            quantiles: number;
            /**
             * Periods
             * @description Forward-return horizons in trading days.
             */
            periods?: number[];
            /**
             * Accept Lookahead
             * @default false
             */
            accept_lookahead: boolean;
            /**
             * Fresh
             * @default false
             */
            fresh: boolean;
        };
        /** DiagnosticResponse */
        DiagnosticResponse: {
            /** Id */
            id: number;
            /** Factor */
            factor: string;
            /** Universe Label */
            universe_label: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Quantiles */
            quantiles: number;
            /** N Observations */
            n_observations: number;
            /** Ic Mean */
            ic_mean: {
                [key: string]: number;
            };
            /** Ic Std */
            ic_std: {
                [key: string]: number;
            };
            /** Ic Ir */
            ic_ir: {
                [key: string]: number;
            };
            /** Top Minus Bottom Pct */
            top_minus_bottom_pct: {
                [key: string]: number;
            };
            /**
             * Verdict
             * @default
             */
            verdict: string;
        };
        /** DiagnosticSummary */
        DiagnosticSummary: {
            /** Id */
            id: number;
            /** Factor */
            factor: string;
            /** Universe Label */
            universe_label: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** N Observations */
            n_observations: number;
            /**
             * Verdict
             * @default
             */
            verdict: string;
        };
        /**
         * FilingNotificationItem
         * @description Row from filing_notifications — what the /research/feed page lists.
         */
        FilingNotificationItem: {
            /** Id */
            id: number;
            /** Ticker */
            ticker: string;
            /** Form */
            form: string;
            /** Accession No */
            accession_no: string;
            /** Filing Date */
            filing_date: string;
            /** Primary Document */
            primary_document?: string | null;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Research Run Id */
            research_run_id?: number | null;
            /** Summary */
            summary?: string | null;
        };
        /** FoldMetric */
        FoldMetric: {
            /** Fold */
            fold: number;
            /** Train Start */
            train_start: string;
            /** Train End */
            train_end: string;
            /** Test Start */
            test_start: string;
            /** Test End */
            test_end: string;
            /** N Train */
            n_train: number;
            /** N Test */
            n_test: number;
            /** Ic Pearson */
            ic_pearson: number;
            /** Ic Spearman */
            ic_spearman: number;
            /** Hit Rate */
            hit_rate: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MLModelsResponse
         * @description List view at /api/ml/models.
         */
        MLModelsResponse: {
            /** Models */
            models?: components["schemas"]["ModelVersionRow"][];
            /**
             * Latest
             * @description One row per distinct model_name — the version the ensemble would use right now.
             */
            latest?: components["schemas"]["ModelVersionRow"][];
            /** Drift */
            drift?: components["schemas"]["ModelDriftSnapshot"][];
        };
        /**
         * MarketRegime
         * @description Snapshot of the broader-market regime indicators a swing trader cares
         *     about. Classification is intentionally crude — the user makes the call;
         *     this just surfaces the inputs.
         */
        MarketRegime: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Label
             * @enum {string}
             */
            label: "bull" | "bear" | "chop" | "unknown";
            /** Spy Price */
            spy_price?: number | null;
            /** Spy Sma200 */
            spy_sma200?: number | null;
            /** Spy Above Sma200 */
            spy_above_sma200?: boolean | null;
            /** Spy Pct From Sma200 */
            spy_pct_from_sma200?: number | null;
            /** Vix Level */
            vix_level?: number | null;
            /** Vix Avg 20D */
            vix_avg_20d?: number | null;
            /** Notes */
            notes?: string[];
        };
        /**
         * ModelDriftSnapshot
         * @description Latest drift status for one registered model.
         */
        ModelDriftSnapshot: {
            /** Model Name */
            model_name: string;
            /** Version */
            version: number;
            /** Training Ic Mean */
            training_ic_mean: number;
            /** Training Ic Std */
            training_ic_std: number;
            /** Rolling Ic */
            rolling_ic: number;
            /** Z Score */
            z_score: number;
            /** Is Drifting */
            is_drifting: boolean;
            /** Window Days */
            window_days: number;
            /** N Observations */
            n_observations: number;
        };
        /**
         * ModelSummaryMetrics
         * @description Headline aggregates over the walk-forward folds.
         */
        ModelSummaryMetrics: {
            /**
             * Mean Ic Pearson
             * @default 0
             */
            mean_ic_pearson: number;
            /**
             * Mean Ic Spearman
             * @default 0
             */
            mean_ic_spearman: number;
            /**
             * Mean Hit Rate
             * @default 0
             */
            mean_hit_rate: number;
            /**
             * N Folds
             * @default 0
             */
            n_folds: number;
            /**
             * Total Test Rows
             * @default 0
             */
            total_test_rows: number;
        };
        /**
         * ModelVersionRow
         * @description One row from ``model_versions`` — for the API list view + /ml page.
         */
        ModelVersionRow: {
            /** Id */
            id: number;
            /** Model Name */
            model_name: string;
            /** Version */
            version: number;
            /**
             * Trained At
             * Format: date-time
             */
            trained_at: string;
            /**
             * Train Window Start
             * Format: date-time
             */
            train_window_start: string;
            /**
             * Train Window End
             * Format: date-time
             */
            train_window_end: string;
            /** Horizon Days */
            horizon_days: number;
            /** Factor Set */
            factor_set: string;
            /** Artifact Path */
            artifact_path: string;
            /** Notes */
            notes?: string | null;
            summary: components["schemas"]["ModelSummaryMetrics"];
            /** Folds */
            folds?: components["schemas"]["FoldMetric"][];
        };
        /**
         * OHLCBar
         * @description One trading day for the chart. Volume is optional — most chart
         *     libraries don't need it for the entry/stop/target overlay view.
         */
        OHLCBar: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume?: number | null;
        };
        /** PaperRecommendationItem */
        PaperRecommendationItem: {
            /** Id */
            id: number;
            /** Ticker */
            ticker: string;
            /** Strategy */
            strategy: string;
            /**
             * Scan Timestamp
             * Format: date-time
             */
            scan_timestamp: string;
            /** Composite Score */
            composite_score: number;
            /**
             * Action
             * @enum {string}
             */
            action: "STRONG BUY" | "BUY" | "HOLD" | "SELL" | "STRONG SELL";
            /** Sub Scores */
            sub_scores?: {
                [key: string]: number;
            };
            /** Entry Price */
            entry_price?: number | null;
            /** Stop Loss */
            stop_loss?: number | null;
            /** Take Profit */
            take_profit?: number | null;
            /** Sector */
            sector?: string | null;
            /** Earnings In Days */
            earnings_in_days?: number | null;
            /**
             * Submitted
             * @default false
             */
            submitted: boolean;
            /** Skip Reason */
            skip_reason?: string | null;
        };
        /** PaperTradeItem */
        PaperTradeItem: {
            /** Id */
            id: number;
            /** Ticker */
            ticker: string;
            /** Qty */
            qty: number;
            /** Entry Price */
            entry_price: number;
            /** Exit Price */
            exit_price: number;
            /**
             * Entry At
             * Format: date-time
             */
            entry_at: string;
            /**
             * Exit At
             * Format: date-time
             */
            exit_at: string;
            /** Hold Days */
            hold_days?: number | null;
            /** Pnl */
            pnl: number;
            /** Pnl Pct */
            pnl_pct: number;
            /** Exit Reason */
            exit_reason?: string | null;
            /** Composite Score */
            composite_score?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** PortfolioStatus */
        PortfolioStatus: {
            account: components["schemas"]["AccountSummary"];
            /** Positions */
            positions: components["schemas"]["Position"][];
            /** N Positions */
            n_positions: number;
        };
        /** Position */
        Position: {
            /** Ticker */
            ticker: string;
            /** Shares */
            shares: number;
            /** Avg Price */
            avg_price: number;
            /** Current Price */
            current_price?: number | null;
            /** Market Value */
            market_value?: number | null;
            /**
             * Unrealized Pnl
             * @default 0
             */
            unrealized_pnl: number;
            /**
             * Unrealized Pnl Pct
             * @default 0
             */
            unrealized_pnl_pct: number;
        };
        /** ResearchAskRequest */
        ResearchAskRequest: {
            /** Question */
            question: string;
            /**
             * Model
             * @description Override default Sonnet 4.6
             */
            model?: string | null;
            /**
             * Max Turns
             * @default 8
             */
            max_turns: number;
            /** Notes */
            notes?: string | null;
        };
        /**
         * ResearchRunDetail
         * @description Detail view — adds tool_calls + (optionally) the transcript.
         */
        ResearchRunDetail: {
            /** Id */
            id: number;
            /** Question */
            question: string;
            /** Model */
            model: string;
            /** Status */
            status: string;
            /** Final Answer */
            final_answer?: string | null;
            /** N Turns */
            n_turns: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Estimated Cost Usd */
            estimated_cost_usd: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Error */
            error?: string | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCallEntry"][];
            /**
             * Transcript
             * @description Full Anthropic message list. Omitted unless include_transcript=true.
             */
            transcript?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * ResearchRunSummary
         * @description List view — light shape, no transcript.
         */
        ResearchRunSummary: {
            /** Id */
            id: number;
            /** Question */
            question: string;
            /** Model */
            model: string;
            /** Status */
            status: string;
            /** Final Answer */
            final_answer?: string | null;
            /** N Turns */
            n_turns: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Estimated Cost Usd */
            estimated_cost_usd: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Error */
            error?: string | null;
        };
        /** ScanRequest */
        ScanRequest: {
            /**
             * Strategy
             * @default swing_trading
             */
            strategy: string;
            /** Budget */
            budget?: number | null;
            /** Theme */
            theme?: string | null;
            /** Sector */
            sector?: string | null;
            /** Top */
            top?: number | null;
            /**
             * Fresh
             * @description Bypass cache, fetch live data
             * @default false
             */
            fresh: boolean;
        };
        /** ScanResponse */
        ScanResponse: {
            /** Run Id */
            run_id: string;
            /** Strategy */
            strategy: string;
            /**
             * Scan Timestamp
             * Format: date-time
             */
            scan_timestamp: string;
            /** N Candidates */
            n_candidates: number;
            /** N Results */
            n_results: number;
            /** Results */
            results: components["schemas"]["ScanResultItem"][];
        };
        /**
         * ScanResultItem
         * @description One recommendation row in a scan response. Permissive shape — accepts
         *     the existing recommender dict; web layer narrows what it renders.
         */
        ScanResultItem: {
            /** Ticker */
            ticker: string;
            /**
             * Action
             * @enum {string}
             */
            action: "STRONG BUY" | "BUY" | "HOLD" | "SELL" | "STRONG SELL";
            /** Composite Score */
            composite_score: number;
            /** Confidence */
            confidence: string;
            /** Sub Scores */
            sub_scores?: {
                [key: string]: number;
            };
            /** Reasoning */
            reasoning?: string[];
            /**
             * Bullish Signals
             * @default 0
             */
            bullish_signals: number;
            /**
             * Bearish Signals
             * @default 0
             */
            bearish_signals: number;
            /** Breakdown */
            breakdown?: {
                [key: string]: unknown;
            }[];
            /** Risk Management */
            risk_management?: {
                [key: string]: unknown;
            };
            /**
             * Sector
             * @default Unknown
             */
            sector: string;
            /**
             * Industry
             * @default Unknown
             */
            industry: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Market Cap */
            market_cap?: number | null;
        };
        /**
         * ScanSummary
         * @description Lighter representation for the GET /api/scans list view.
         */
        ScanSummary: {
            /** Run Id */
            run_id: string;
            /** Strategy */
            strategy: string;
            /**
             * Scan Timestamp
             * Format: date-time
             */
            scan_timestamp: string;
            /** N Candidates */
            n_candidates: number;
            /** Top Ticker */
            top_ticker?: string | null;
            /** Top Score */
            top_score?: number | null;
        };
        /** ScoreCalibration */
        ScoreCalibration: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** N Total Trades */
            n_total_trades: number;
            /** Buckets */
            buckets?: components["schemas"]["CalibrationBucket"][];
            /** Notes */
            notes?: string[];
        };
        /** SectorMetric */
        SectorMetric: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Last Close */
            last_close?: number | null;
            /** Sma50 */
            sma50?: number | null;
            /** Above Sma50 */
            above_sma50?: boolean | null;
            /** Return 1D Pct */
            return_1d_pct?: number | null;
            /** Return 5D Pct */
            return_5d_pct?: number | null;
            /** Return 21D Pct */
            return_21d_pct?: number | null;
        };
        /** SectorsResponse */
        SectorsResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Sectors */
            sectors?: components["schemas"]["SectorMetric"][];
        };
        /** StockDetail */
        StockDetail: {
            /** Ticker */
            ticker: string;
            /** @description Engine's most recent recommendation row for this ticker, or null if it has never appeared in a stored scan_run. */
            latest_recommendation?: components["schemas"]["ScanResultItem"] | null;
            /** Scan Run Id */
            scan_run_id?: string | null;
            /** Scan Strategy */
            scan_strategy?: string | null;
            /** Scan Timestamp */
            scan_timestamp?: string | null;
            /**
             * History
             * @description Recent OHLC bars for charting. Window is controlled by the endpoint's `history_days` query param (default 120).
             */
            history?: components["schemas"]["OHLCBar"][];
        };
        /**
         * SummarizeNotificationResponse
         * @description What ``POST /api/research/notifications/{id}/summarize`` returns:
         *     the notification (now linked to a run) plus the run detail itself.
         */
        SummarizeNotificationResponse: {
            notification: components["schemas"]["FilingNotificationItem"];
            run: components["schemas"]["ResearchRunDetail"];
        };
        /** ToolCallEntry */
        ToolCallEntry: {
            /** Tool */
            tool: string;
            /** Input */
            input?: {
                [key: string]: unknown;
            };
            /**
             * Is Error
             * @default false
             */
            is_error: boolean;
            /**
             * Result Summary
             * @default
             */
            result_summary: string;
        };
        /** TradeNotesUpdate */
        TradeNotesUpdate: {
            /**
             * Notes
             * @description Set to null/omit to clear; otherwise replaces the journal entry.
             */
            notes?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_portfolio_api_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioStatus"];
                };
            };
        };
    };
    get_positions_api_portfolio_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Position"][];
                };
            };
        };
    };
    get_account_api_portfolio_account_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"];
                };
            };
        };
    };
    list_scans_api_scans_get: {
        parameters: {
            query?: {
                strategy?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_scan_api_scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_scans__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_detail_api_stocks__ticker__get: {
        parameters: {
            query?: {
                history_days?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backtests_api_backtests_get: {
        parameters: {
            query?: {
                strategy?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_backtest_api_backtests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_api_backtests__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_diagnostics_api_diagnostics_get: {
        parameters: {
            query?: {
                factor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_diagnostic_api_diagnostics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnosticRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diagnostic_api_diagnostics__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recommendations_api_recommendations_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                strategy?: string | null;
                submitted_only?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperRecommendationItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendation_api_recommendations__rec_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rec_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperRecommendationItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_portfolio_api_stream_portfolio_get: {
        parameters: {
            query?: {
                poll_seconds?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_heartbeat_api_stream_heartbeat_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stream_prices_api_stream_prices_get: {
        parameters: {
            query: {
                /** @description Comma-separated symbols (e.g. AAPL,MSFT,TSLA) */
                symbols: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_trade_updates_api_stream_trade_updates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stream_scan_api_stream_scan_get: {
        parameters: {
            query?: {
                strategy?: string;
                budget?: number | null;
                theme?: string | null;
                sector?: string | null;
                top?: number | null;
                fresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_regime_api_market_regime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketRegime"];
                };
            };
        };
    };
    get_sectors_api_market_sectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorsResponse"];
                };
            };
        };
    };
    score_calibration_api_analytics_calibration_get: {
        parameters: {
            query?: {
                min_score?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreCalibration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trades_api_trades_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                min_score?: number | null;
                has_notes?: boolean | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperTradeItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trade_notes_api_trades__trade_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeNotesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperTradeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ml_models_api_ml_models_get: {
        parameters: {
            query?: {
                model_name?: string | null;
                limit?: number;
                window_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MLModelsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_research_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchAskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_stream_api_research_ask_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchAskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_research_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_research_runs__run_id__get: {
        parameters: {
            query?: {
                include_transcript?: boolean;
            };
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_research_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
                ticker?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilingNotificationItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summarize_notification_api_research_notifications__notification_id__summarize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummarizeNotificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_notifications_api_research_notifications_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    monitor_status_api_research_monitor_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
