"""
Sync Alpaca paper account state into the local project.

`sync_portfolio` pulls open positions and rewrites config/portfolio.yaml so
that `portfolio --analyze` reflects what was actually filled. The original
file is backed up to portfolio.yaml.bak before any rewrite.
"""

import shutil
import logging
from pathlib import Path

import yaml
from rich.table import Table
from rich import box

from src.broker.alpaca_client import AlpacaClient
from src.display.cli_output import console

logger = logging.getLogger(__name__)


def sync_portfolio(config, write=True):
    """
    Pull positions + cash from Alpaca paper account.
    If write=True, rewrite config/portfolio.yaml (with .bak backup).
    Returns (account_dict, positions_list).
    """
    client = AlpacaClient()
    account = client.get_account()
    positions = client.get_positions()

    _display_account(account)
    _display_positions(positions)

    if not write:
        return account, positions

    portfolio_path = config.config_dir / "portfolio.yaml"
    existing = _load_existing(portfolio_path)
    backup_path = portfolio_path.with_suffix(".yaml.bak")
    if portfolio_path.exists():
        shutil.copy2(portfolio_path, backup_path)
        console.print(f"  [dim]Backup: {backup_path.name}[/dim]")

    new_doc = {
        "total_cash_available": round(account["cash"], 2),
        "holdings": [
            {
                "ticker": p["ticker"],
                "shares": round(p["shares"], 4),
                "avg_price": round(p["avg_price"], 2),
            }
            for p in positions
        ],
        "action_thresholds": existing.get("action_thresholds", {
            "add_score": 65,
            "hold_min_score": 40,
            "trim_score": 35,
            "overweight_pct": 15,
            "underweight_pct": 3,
        }),
    }

    with open(portfolio_path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by `paper sync` from Alpaca paper account.\n")
        f.write("# Edit at your own risk — the next sync will overwrite holdings + cash.\n\n")
        yaml.safe_dump(new_doc, f, sort_keys=False, default_flow_style=False)

    console.print(
        f"  [green]Wrote {len(positions)} position(s) and "
        f"${account['cash']:,.2f} cash to portfolio.yaml[/green]\n"
    )
    return account, positions


def _load_existing(path):
    if not path.exists():
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _display_account(account):
    table = Table(box=box.ROUNDED, show_header=False, title="Alpaca Paper Account")
    table.add_column("Field", style="cyan")
    table.add_column("Value", justify="right")
    table.add_row("Account #", account["account_number"])
    table.add_row("Status", account["status"])
    table.add_row("Equity", f"${account['equity']:,.2f}")
    table.add_row("Cash", f"${account['cash']:,.2f}")
    table.add_row("Buying Power", f"${account['buying_power']:,.2f}")
    table.add_row("Long Market Value", f"${account['long_market_value']:,.2f}")
    console.print(table)


def _display_positions(positions):
    if not positions:
        console.print("  [dim]No open positions in Alpaca paper account.[/dim]\n")
        return
    table = Table(box=box.ROUNDED, title=f"Open Positions ({len(positions)})")
    table.add_column("Ticker", style="bold cyan")
    table.add_column("Shares", justify="right")
    table.add_column("Avg Price", justify="right")
    table.add_column("Current", justify="right")
    table.add_column("Market Value", justify="right")
    table.add_column("P&L $", justify="right")
    table.add_column("P&L %", justify="right")

    for p in positions:
        pnl_color = "green" if p["unrealized_pnl"] >= 0 else "red"
        table.add_row(
            p["ticker"],
            f"{p['shares']:.4g}",
            f"${p['avg_price']:.2f}",
            f"${p['current_price']:.2f}" if p["current_price"] else "—",
            f"${p['market_value']:,.2f}" if p["market_value"] else "—",
            f"[{pnl_color}]${p['unrealized_pnl']:+,.2f}[/{pnl_color}]",
            f"[{pnl_color}]{p['unrealized_pnl_pct']:+.2f}%[/{pnl_color}]",
        )
    console.print(table)
    console.print()
